platform: x64
version: '{build}'

install:
- PATH=C:\mongodb\bin\;%PATH%
- java -version
- mongod --version
- ps: Install-Product node 6
- npm install bower gulp -g
- npm install
- bower install

build_script:
- npm run build:prod

test_script:
- npm run test:property
- npm test
